# Generated by Django 4.1.4 on 2022-12-18 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_save'),
    ]

    operations = [
        migrations.RenameField(
            model_name='save',
            old_name='save',
            new_name='save_status',
        ),
    ]
